version: '3'
services:
 # mongo config server
  34mongosourcecfg1:
    container_name: 34mongosourcecfg1
    hostname: 34mongosourcecfg1
    image: mongo:3.4.24
    command: mongod --configsvr --replSet 34mongosourcers1conf --dbpath /data/db --port 27321
    ports:
      - 27321:27321
    volumes:
      - ~/mongo_source_cluster_34/config1:/data/db

  34mongosourcecfg2:
    container_name: 34mongosourcecfg2
    hostname: 34mongosourcecfg2
    image: mongo:3.4.24
    command: mongod --configsvr --replSet 34mongosourcers1conf --dbpath /data/db --port 27321
    ports:
      - 27322:27321
    volumes:
      - ~/mongo_source_cluster_34/config2:/data/db

  34mongosourcecfg3:
    container_name: 34mongosourcecfg3
    hostname: 34mongosourcecfg3
    image: mongo:3.4.24
    command: mongod --configsvr --replSet 34mongosourcers1conf --dbpath /data/db --port 27321
    ports:
      - 27323:27321
    volumes:
      - ~/mongo_source_cluster_34/config3:/data/db

# replica set shard 1
  34mongosourcers1n1:
    container_name: 34mongosourcers1n1
    hostname: 34mongosourcers1n1
    image: mongo:3.4.24
    command: mongod --shardsvr --replSet 34mongosourcers1 --dbpath /data/db --port 27324
    ports:
      - 27324:27324
    volumes:
      - ~/mongo_source_cluster_34/data1:/data/db

  34mongosourcers1n2:
    container_name: 34mongosourcers1n2
    hostname: 34mongosourcers1n2
    image: mongo:3.4.24
    command: mongod --shardsvr --replSet 34mongosourcers1 --dbpath /data/db --port 27324
    ports:
      - 27325:27324
    volumes:
      - ~/mongo_source_cluster_34/data2:/data/db

  34mongosourcers1n3:
    container_name: 34mongosourcers1n3
    hostname: 34mongosourcers1n3
    image: mongo:3.4.24
    command: mongod --shardsvr --replSet 34mongosourcers1 --dbpath /data/db --port 27324
    ports:
      - 27326:27324
    volumes:
      - ~/mongo_source_cluster_34/data3:/data/db

# mongos router
  34mongossource1:
    container_name: 34mongossource1
    hostname: 34mongossource1
    image: mongo:3.4.24
    depends_on:
      - 34mongosourcecfg1
      - 34mongosourcecfg2
    command: mongos --configdb 34mongosourcers1conf/34mongosourcecfg1:27321,34mongosourcecfg2:27321,34mongosourcecfg3:27321 --port 27317
    ports:
      - 27317:27317
